force-app/main/default/objects/SM_QuestionSet__c/SM_QuestionSet__c.object-meta.xml
<CustomObject>
    <description>Custom question set definition for P2P or P2C</description>
    <label>Question Set</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SM_QuestionSetGroup__c/SM_QuestionSetGroup__c.object-meta.xml
<CustomObject>
    <description>Group of questions</description>
    <label>Question Set Group</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Set Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SM_QuestionSetGroup__c/fields/GroupNumber__c.field-meta.xml
<CustomField>
    <fullName>GroupNumber__c</fullName>
    <label>Group Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_QuestionSetGroup__c/fields/QuestionSet__c.field-meta.xml
<CustomField>
    <fullName>QuestionSet__c</fullName>
    <label>Question Set</label>
    <referenceTo>SM_QuestionSet__c</referenceTo>
    <relationshipLabel>Question Set Groups</relationshipLabel>
    <relationshipName>Question_Set_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SM_QuestionSetQuestion__c/SM_QuestionSetQuestion__c.object-meta.xml
<CustomObject>
    <label>Question Set Question</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Set Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SM_QuestionSetQuestion__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>SM_QuestionSetGroup__c</referenceTo>
    <relationshipLabel>Question Set Questions</relationshipLabel>
    <relationshipName>Question_Set_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SM_QuestionSetQuestion__c/fields/QuestionNumber__c.field-meta.xml
<CustomField>
    <fullName>QuestionNumber__c</fullName>
    <label>Question Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_QuestionSetQuestion__c/fields/QuestionSet__c.field-meta.xml
<CustomField>
    <fullName>QuestionSet__c</fullName>
    <label>Question Set</label>
    <referenceTo>SM_QuestionSet__c</referenceTo>
    <relationshipLabel>Question Set Questions</relationshipLabel>
    <relationshipName>Question_Set_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuestionController.cls
public without sharing class QuestionController {

    //Fetch all Questions
    @AuraEnabled(cacheable=true)
    public static List<SM_QuestionSetQuestion__c> getAllQuestions() {
        string query = 'SELECT Id, Name, QuestionNumber__c, Group__c, Group__r.Name FROM SM_QuestionSetQuestion__c';
		return Database.query(query);
    }

    //Fetch all QuestionGroups
    @AuraEnabled(cacheable=true)
    public static List<SM_QuestionSetGroup__c> getAllQuestionGroups() {
        string query = 'SELECT Id, Name, GroupNumber__c FROM SM_QuestionSetGroup__c ORDER BY GroupNumber__c ASC';
		return Database.query(query);
    }

    //Reset all Questions to New status
    @AuraEnabled
    public static void resetAllQuestionsNew() {
      list<SM_QuestionSetQuestion__c> allQuestions = [SELECT Id, Name, QuestionNumber__c, Group__c FROM SM_QuestionSetQuestion__c];
      for (SM_QuestionSetQuestion__c q : allQuestions) {
        q.Group__c = null;
      }
		  Database.update(allQuestions);
    }

    @AuraEnabled(cacheable=true)
    public static SM_QuestionSet__c getQuestionSetData() {
        string query = 
            'SELECT Id, Name, ' +
              '(SELECT Id, Name, GroupNumber__c FROM Question_Set_Groups__r ORDER BY GroupNumber__c), ' +
              '(SELECT Id, Name, QuestionNumber__c, Group__c FROM Question_Set_Questions__r ORDER BY QuestionNumber__c) ' +
            'FROM SM_QuestionSet__c ' +
            'WHERE Id = \'a023D000004aGIiQAM\'';
        return Database.query(query);
    }
}